/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;



/**
 *
 * @author BR0706686541
 */
public class Calculator extends javax.swing.JFrame {

    public int codigo;
    public String textoAnterior;
    public Double valorFinal;
    public String mostrarValorFinal;
    public String valorTotalAnterior;
    public Double valor1;
    public Double valor2;
    public int comparar = 0;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        txf_valor.setEnabled(false);
        setTitle("Calculadora");
        txf_valor.setText(Integer.toString(comparar));
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_fundo = new javax.swing.JPanel();
        txf_valor = new javax.swing.JFormattedTextField();
        btn_igual = new javax.swing.JButton();
        btn_um = new javax.swing.JButton();
        btn_dois = new javax.swing.JButton();
        btn_tres = new javax.swing.JButton();
        btn_quatro = new javax.swing.JButton();
        btn_cinco = new javax.swing.JButton();
        btn_seis = new javax.swing.JButton();
        btn_sete = new javax.swing.JButton();
        btn_oito = new javax.swing.JButton();
        btn_nove = new javax.swing.JButton();
        btn_soma = new javax.swing.JButton();
        btn_subtracao = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_backSpace = new javax.swing.JButton();
        btn_virgula = new javax.swing.JButton();
        lbl_valorAnterior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_fundo.setBackground(new java.awt.Color(153, 153, 153));
        pnl_fundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_fundo.setForeground(new java.awt.Color(255, 255, 255));

        txf_valor.setBackground(new java.awt.Color(255, 255, 255));
        txf_valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txf_valor.setForeground(new java.awt.Color(255, 255, 255));
        txf_valor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txf_valor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txf_valor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btn_igual.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_igual.setText("=");
        btn_igual.setBorder(new javax.swing.border.MatteBorder(null));
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_um.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_um.setText("1");
        btn_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_umActionPerformed(evt);
            }
        });

        btn_dois.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_dois.setText("2");
        btn_dois.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doisActionPerformed(evt);
            }
        });

        btn_tres.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_tres.setText("3");
        btn_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tresActionPerformed(evt);
            }
        });

        btn_quatro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_quatro.setText("4");
        btn_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quatroActionPerformed(evt);
            }
        });

        btn_cinco.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_cinco.setText("5");
        btn_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cincoActionPerformed(evt);
            }
        });

        btn_seis.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_seis.setText("6");
        btn_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seisActionPerformed(evt);
            }
        });

        btn_sete.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sete.setText("7");
        btn_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seteActionPerformed(evt);
            }
        });

        btn_oito.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_oito.setText("8");
        btn_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oitoActionPerformed(evt);
            }
        });

        btn_nove.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_nove.setText("9");
        btn_nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_noveActionPerformed(evt);
            }
        });

        btn_soma.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_soma.setText("+");
        btn_soma.setBorder(new javax.swing.border.MatteBorder(null));
        btn_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_somaActionPerformed(evt);
            }
        });

        btn_subtracao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_subtracao.setText("-");
        btn_subtracao.setBorder(new javax.swing.border.MatteBorder(null));
        btn_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subtracaoActionPerformed(evt);
            }
        });

        btn_zero.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_zero.setText("0");
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });

        btn_multiplicar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_multiplicar.setText("X");
        btn_multiplicar.setBorder(new javax.swing.border.MatteBorder(null));
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_dividir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_dividir.setText("/");
        btn_dividir.setBorder(new javax.swing.border.MatteBorder(null));
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });

        btn_limpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_limpar.setText("Clear");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_backSpace.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_backSpace.setText("C");
        btn_backSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backSpaceActionPerformed(evt);
            }
        });

        btn_virgula.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btn_virgula.setText(",");
        btn_virgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_virgulaActionPerformed(evt);
            }
        });

        lbl_valorAnterior.setBackground(new java.awt.Color(255, 255, 255));
        lbl_valorAnterior.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnl_fundoLayout = new javax.swing.GroupLayout(pnl_fundo);
        pnl_fundo.setLayout(pnl_fundoLayout);
        pnl_fundoLayout.setHorizontalGroup(
            pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fundoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_valorAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_fundoLayout.createSequentialGroup()
                .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btn_backSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_um, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addComponent(btn_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_fundoLayout.createSequentialGroup()
                                .addComponent(btn_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_fundoLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btn_virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_fundoLayout.setVerticalGroup(
            pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_fundoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_limpar)
                    .addComponent(lbl_valorAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_backSpace)
                .addGap(20, 20, 20)
                .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_fundoLayout.createSequentialGroup()
                                .addComponent(btn_um, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_fundoLayout.createSequentialGroup()
                                .addComponent(btn_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_fundoLayout.createSequentialGroup()
                                .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_fundoLayout.createSequentialGroup()
                        .addComponent(btn_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_umActionPerformed
           textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("1");
                } else {
                 txf_valor.setText(textoAnterior + "1");
                }
    }//GEN-LAST:event_btn_umActionPerformed

    private void btn_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doisActionPerformed
         textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("2");
                } else {
                 txf_valor.setText(textoAnterior + "2");
                }
    }//GEN-LAST:event_btn_doisActionPerformed

    private void btn_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tresActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("3");
                } else {
                 txf_valor.setText(textoAnterior + "3");
                }
    }//GEN-LAST:event_btn_tresActionPerformed

    private void btn_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quatroActionPerformed
       
        textoAnterior = txf_valor.getText();   
         
        if(textoAnterior == null  || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                       
                     txf_valor.setText("4");
                } else {
                
                 txf_valor.setText(textoAnterior + "4");
                }
    }//GEN-LAST:event_btn_quatroActionPerformed

    private void btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cincoActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("5");
                } else {
                 txf_valor.setText(textoAnterior + "5");
                }
    }//GEN-LAST:event_btn_cincoActionPerformed

    private void btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seisActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("6");
                } else {
                 txf_valor.setText(textoAnterior + "6");
                }
    }//GEN-LAST:event_btn_seisActionPerformed

    private void btn_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seteActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("7");
                } else {
                 txf_valor.setText(textoAnterior + "7");
                }
    }//GEN-LAST:event_btn_seteActionPerformed

    private void btn_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oitoActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("8");
                } else {
                 txf_valor.setText(textoAnterior + "8");
                }
    }//GEN-LAST:event_btn_oitoActionPerformed

    private void btn_noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_noveActionPerformed
         textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("9");
                } else {
                 txf_valor.setText(textoAnterior + "9");
                }
    }//GEN-LAST:event_btn_noveActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
          textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty() || textoAnterior.equals(Integer.toString(comparar))){
                     txf_valor.setText("0");
                } else {
                 txf_valor.setText(textoAnterior + "0");
                }
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
       txf_valor.setText("0");
       textoAnterior = "";
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_somaActionPerformed
          valorTotalAnterior = txf_valor.getText();
          lbl_valorAnterior.setText(valorTotalAnterior + " +");
          txf_valor.setValue("0");
          
          codigo = 1;
          
    }//GEN-LAST:event_btn_somaActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        lbl_valorAnterior.setText("");
        
     switch(codigo){
         
         case 1:
         valor1 = Double.parseDouble(valorTotalAnterior);
         valor2 = Double.parseDouble(txf_valor.getText());
         valorFinal = valor1 + valor2;
         mostrarValorFinal = Double.toString(valorFinal);
         txf_valor.setText(mostrarValorFinal);
        break;
         case 2:
         valor1 = Double.parseDouble(valorTotalAnterior);
         valor2 = Double.parseDouble(txf_valor.getText());
         valorFinal = valor1 - valor2;
         mostrarValorFinal = Double.toString(valorFinal);
         txf_valor.setText(mostrarValorFinal);
         break;
          case 3:
         valor1 = Double.parseDouble(valorTotalAnterior);
         valor2 = Double.parseDouble(txf_valor.getText());
         valorFinal = valor1 * valor2;
         mostrarValorFinal = Double.toString(valorFinal);
         txf_valor.setText(mostrarValorFinal);
         break;
          case 4:
         valor1 = Double.parseDouble(valorTotalAnterior);
         valor2 = Double.parseDouble(txf_valor.getText());
         valorFinal = valor1 / valor2;
         mostrarValorFinal = Double.toString(valorFinal);
         txf_valor.setText(mostrarValorFinal);
         break;
         
     } 
       
          String limparZero = txf_valor.getText();
        String novoLimpo = limparZero.substring (limparZero.length()-2);
       
            if(".0".equals(novoLimpo)){
           novoLimpo = limparZero.substring(0,limparZero.length()-2);
                txf_valor.setText(novoLimpo);
            }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subtracaoActionPerformed
         valorTotalAnterior = txf_valor.getText();
         lbl_valorAnterior.setText(valorTotalAnterior + " -");
          txf_valor.setValue("0");
          
          codigo = 2;
    }//GEN-LAST:event_btn_subtracaoActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
         valorTotalAnterior = txf_valor.getText();
         lbl_valorAnterior.setText(valorTotalAnterior + " *");
          txf_valor.setValue("0");
          
          codigo = 3;
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
         valorTotalAnterior = txf_valor.getText();
         lbl_valorAnterior.setText(valorTotalAnterior + " /");
          txf_valor.setValue("0");
          
          codigo = 4;
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_backSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backSpaceActionPerformed
        String apagar = txf_valor.getText();
        String nova = apagar.substring(0,apagar.length()-1);
        txf_valor.setText(nova);
         if(nova == null || nova.isEmpty() ){
                     txf_valor.setText("0");
         }
    }//GEN-LAST:event_btn_backSpaceActionPerformed

    private void btn_virgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_virgulaActionPerformed
        textoAnterior = txf_valor.getText();   
        
        if(textoAnterior == null || textoAnterior.isEmpty()){
                     txf_valor.setText("0.");
                } else {
                 txf_valor.setText(textoAnterior + ".");
                }
    }//GEN-LAST:event_btn_virgulaActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (Doubleroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
                
            
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backSpace;
    private javax.swing.JButton btn_cinco;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_dois;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_nove;
    private javax.swing.JButton btn_oito;
    private javax.swing.JButton btn_quatro;
    private javax.swing.JButton btn_seis;
    private javax.swing.JButton btn_sete;
    private javax.swing.JButton btn_soma;
    private javax.swing.JButton btn_subtracao;
    private javax.swing.JButton btn_tres;
    private javax.swing.JButton btn_um;
    private javax.swing.JButton btn_virgula;
    private javax.swing.JButton btn_zero;
    private javax.swing.JLabel lbl_valorAnterior;
    private javax.swing.JPanel pnl_fundo;
    private javax.swing.JFormattedTextField txf_valor;
    // End of variables declaration//GEN-END:variables
}
